apiVersion: v1
kind: Service
metadata:
  name: single-page-app-service
spec:
  type: LoadBalancer
  selector:
    app: single-page-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
